---
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Se creó un bucle espacio temporal
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: p1 sigue apuntando a num
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: p1 ya no apunta a num
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: p3 apunta a num
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Todas  las anteriores
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Las dos anteriores
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: La respuesta es Japón
  checked: true
name: Se pueden crear bucles?
